### ISSUE TITLE
Must have one file in data directory

### ISSUE THREAD

**Issue by yyeahoo** [ayushsharma82/ESP-DASH#2] opened 2017-11-12 16:27 UTC
This is awesome....  however I had at least one issue getting everything to work (great instructions).

In  the data directory if you only have a dash folder the "ESP8266 Sketch data upload" thinks there is nothing to upload.  I added a text file in the data directory and it works perfect. 

![no files](https://user-images.githubusercontent.com/15075269/32701014-07c1d76a-c794-11e7-9822-51bf321faff2.png)

**Comment by yyeahoo** [comment] 2017-11-12 16:55
Issues continued... 
I used a WeMos D1 Mini to run the Basic.ino Sketch... works great except Switching Wifi, Rebooting, and update.   I'm using Arduino IDE version 1.8.4.
All the actions seem to cause the sketch to crash.   Some of this may be an issue with the Wemos D1 mini.... I have not been successful with attempts to do software reboots.   I will investigate further. 

Another issue to be aware of but not a ESP-DASH issue.   The Basic.ino will overwrite any data in SPPIFFS. Sketch should check for existing files and add the dash files with FTPServer/Filezilla or via SPIFFS  to avoid over writing existing files.   

Updating the tabs with ESP-DASH is awesome approach for displaying sensor data.

**Comment by ayushsharma82** [comment] 2017-11-13 12:38
@yyeahoo
Problem1 : 
Make Sure you are clicking Upload SPIFFS in Example Sketch only. ( The Example Sketch. Not the Example which is saved later on clicking 'save as')

Problem2:   
This is Weird . I have these Working without any problems @ Arduino IDE 1.8.5. 
and on Sketch Upload, The SPIFFS should not be overwritten . SPIFFS upload is a different process.
( Please keep in Mind that 'Upload SPIFFS data' will offcourse delete data as it creates a full SPIFFS image )
Add your previous data in SPIFFS data folder before uploading.

**Comment by ayushsharma82** [comment] 2017-11-13 12:40
@yyeahoo After Updating my Arduino IDE. i am getting the Same SPIFFS Problem 1. Thanks for Letting us know. i will fix it soon.

**Comment by ayushsharma82** [comment] 2017-11-13 12:46
@yyeahoo  For Problem 2 . Make Sure you have javascript enabled in your browser.

**Comment by ayushsharma82** [comment] 2017-11-13 12:51
Fixed Empty SPIFFS Issue.

**Comment by ayushsharma82** [comment] 2017-11-13 12:59
On More Research i think we downloaded a previous release of ESP8266 MKSPIFFS Software. I have updated Library with new links in example and Please download new version  0.3.0 from here and try again. this does not gives empty folder error.:
 https://github.com/esp8266/arduino-esp8266fs-plugin/releases

**Comment by ayushsharma82** [comment] 2017-11-14 18:43
I Think the issue is fixed now...

**Closed by ayushsharma82** 2017-11-14 18:43 UTC
Labels: bug
